import { initializeApp, getApp, getApps } from "firebase/app";
import { getFirestore } from "firebase/firestore";
import { getAuth } from "firebase/auth";

// Read from config file generated by set_up_firebase
const firebaseConfig = {
  apiKey: "AIzaSyCdQh-N34S_ixPFOJHB7iC3f7HDY5_QY30",
  authDomain: "serene-academy-cdzmz.firebaseapp.com",
  projectId: "serene-academy-cdzmz",
  storageBucket: "serene-academy-cdzmz.firebasestorage.app",
  messagingSenderId: "1063892680280",
  appId: "1:1063892680280:web:9ad882e48a8d4cbc34942d"
};

const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();

// Use the specific firestoreDatabaseId generated for the database if available
export const db = getFirestore(app, "ai-studio-55fb22db-ae3d-454c-9f67-78e40edd4034");
export const auth = getAuth(app);
